spring:
  #  security:
  #    user:
  #      name: yunxia
  #      password: 768874
  datasource:
    url: jdbc:mariadb://localhost:3306/lib
    driver-class-name: org.mariadb.jdbc.Driver
    username: yunxia
    password: 768874
  # https://juejin.cn/post/7076244567569203208
  mail:
    host: smtp.qq.com
    port: 465
    username: 1635276938@qq.com
    password: urklqvvsbpqeefed
    default-encoding: utf-8
    baseHost: localhost:5173 # diy
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
  mvc:
    format:
      date: "yyyy-MM-dd"
      time: "HH:mm:ss"
      datetime: "yyyy-MM-dd HH:mm:ss"
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 350MB

token:
  validityTime:
    short: 86_400_000
    long: 604_800_000

# mybatis 相关配置
mybatis:
  mapper-locations: classpath:com/lib/bookbrain/dao/*.xml
  configuration:
    #    命令行输出 sql 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    开启驼峰命名和下划线的匹配：user_id => userId
    map-underscore-to-camel-case: true


# 日志
logging:
  level:
    # 事务日志
    org.springframework.jdbc.support.JDBCTransactionManager: debug
  # 输出日志
  pattern:
    dateformat: YYYY-MM-DD mm:hh:ss

# 端口
server:
  port: 9090

# 异步线程配置
async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 5
      # 配置最大线程数
      max_pool_size: 5
      # 配置队列大小
      queue_capacity: 99999
      # 配置线程池中的线程的名称前缀
      name:
        prefix: async-service-